### ISSUE TITLE
经常报java.lang.Thread cannot be cast to java.lang.Comparable

### ISSUE THREAD

**Issue by zwllxs** [xiaolyuh/layering-cache#11]
Caused by: java.lang.ClassCastException: java.lang.Thread cannot be cast to java.lang.Comparable
at java.util.concurrent.ConcurrentSkipListMap.cpr(ConcurrentSkipListMap.java:655)
at java.util.concurrent.ConcurrentSkipListMap.doPut(ConcurrentSkipListMap.java:899)
at java.util.concurrent.ConcurrentSkipListMap.putIfAbsent(ConcurrentSkipListMap.java:1979)
at java.util.concurrent.ConcurrentSkipListSet.add(ConcurrentSkipListSet.java:241)
at xxxxx.support.AwaitThreadContainer.await(AwaitThreadContainer.java:38)

**Comment by xiaolyuh123** [comment]
能说下你的操作步骤吗？

发自我的 iPhone

**Comment by xiaolyuh123** [comment]
不能复现
