### ISSUE TITLE
运行一段时间后，频繁出现 Command timed out after 1 minute(s)

### ISSUE THREAD

**Issue by qinchz** [xiaolyuh/layering-cache#35]
大佬好，运行一段时间后，会频繁出现以下异常，应用重启后又正常了，请问可能什么问题？

com.github.xiaolyuh.redis.clinet.RedisClientException: Command timed out after 1 minute(s)
	at com.github.xiaolyuh.redis.clinet.SingleRedisClient.llen(SingleRedisClient.java:210)
	at com.github.xiaolyuh.listener.RedisMessageService.pullMessage(RedisMessageService.java:61)
	at com.github.xiaolyuh.listener.RedisMessageListener.message(RedisMessageListener.java:43)
	at com.github.xiaolyuh.listener.RedisMessageListener.message(RedisMessageListener.java:19)
	at io.lettuce.core.pubsub.PubSubEndpoint.notifyListeners(PubSubEndpoint.java:185)
	at io.lettuce.core.pubsub.PubSubEndpoint.notifyMessage(PubSubEndpoint.java:174)
	at io.lettuce.core.pubsub.PubSubCommandHandler.doNotifyMessage(PubSubCommandHandler.java:214)
	at io.lettuce.core.pubsub.PubSubCommandHandler.decode(PubSubCommandHandler.java:120)
	at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:565)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)

Caused by: io.lettuce.core.RedisCommandTimeoutException: Command timed out after 1 minute(s)
	at io.lettuce.core.ExceptionFactory.createTimeoutException(ExceptionFactory.java:51)
	at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:114)
	at io.lettuce.core.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:69)
	at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
	at com.sun.proxy.$Proxy209.llen(Unknown Source)
	at com.github.xiaolyuh.redis.clinet.SingleRedisClient.llen(SingleRedisClient.java:206)
	... 24 common frames omitted

**Comment by xiaolyuh123** [comment]
你是不是断过网


发自我的iPhone

**Comment by qinchz** [comment]
有可能断过网，不过没有重连机制吗？

**Comment by xiaolyuh123** [comment]
重连之前就会出现这个


发自我的iPhone

**Comment by qinchz** [comment]
奥奥，不过我的网络应该早就恢复了，但是还是会报这个错~

**Comment by xiaolyuh123** [comment]
应是到redis的网络还没通
