### ISSUE TITLE
spring boot 2.1.1  redis报错

### ISSUE THREAD

**Issue by dongjiyan** [xiaolyuh/layering-cache#4]
项目中使用 spring-data-redis 2.1.1版本，在获取返回值为null时报错，错误信息如下,希望能够得到解决谢谢
```java
java.lang.NoSuchMethodError: org.springframework.data.redis.core.RedisTemplate.delete(Ljava/lang/Object;)V

	at com.github.xiaolyuh.cache.redis.RedisCache.putValue(RedisCache.java:270)
	at com.github.xiaolyuh.cache.redis.RedisCache.loaderAndPutValue(RedisCache.java:254)
	at com.github.xiaolyuh.cache.redis.RedisCache.executeCacheMethod(RedisCache.java:240)
	at com.github.xiaolyuh.cache.redis.RedisCache.get(RedisCache.java:154)
	at com.github.xiaolyuh.cache.LayeringCache.get(LayeringCache.java:128)
	at com.github.xiaolyuh.aspect.LayeringAspect.executeCacheable(LayeringAspect.java:186)
	at com.github.xiaolyuh.aspect.LayeringAspect.cacheablePointcut(LayeringAspect.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
```

```java
@Configuration
public class RedisConfig {

    @Bean(name = "redisTemplate")
    public RedisTemplate<String, Object> redisTemplate(
            RedisConnectionFactory redisConnectionFactory) {
        RedisTemplate<String, Object> template = new RedisTemplate<>();
        template.setConnectionFactory(redisConnectionFactory);
        StringRedisSerializer keySer = new StringRedisSerializer();
        template.setKeySerializer(keySer);
        KryoRedisSerializer<Object> kryoRedisSerializer = new KryoRedisSerializer<>(Object.class);
        template.setValueSerializer(kryoRedisSerializer);
        template.setHashValueSerializer(kryoRedisSerializer);
        template.setHashKeySerializer(keySer);
        template.setDefaultSerializer(keySer);
        return template;
    }

}
```

**Comment by dongjiyan** [comment]
能不能 用spring 2.1.1版本和spring-data-redis的相同版本，构建一下

**Comment by xiaolyuh123** [comment]
实在不好意思  这个框架是在springboot 1.5的基础上开发的  我尽快对spring boot2.0做兼容


发自我的 iPhone

**Comment by xiaolyuh123** [comment]
你好你可以依赖最新的2.0.0的包，它已经支持spring boot2.0了

**Comment by dongjiyan** [comment]
十分感谢，有空可以交流一下，log的debug的信息，用JSON直接序列化出来，再一定程度上还是消耗了CPU资源，可以用log.isDebug()出来一下

**Comment by tt5753** [comment]
redisTemplate.delete()；//这样就会报错
boolean flag = redisTemplate.delete()；//这样不报错

**Comment by xiaolyuh123** [comment]
没看明白

发自我的iPhone
