### ISSUE TITLE
spring-data-reids-2.1.3.RELEASE报CacheStatsInfo不能被序列化

### ISSUE THREAD

**Issue by wuying8** [xiaolyuh/layering-cache#6]
代码段：
```
// 将缓存统计数据写到redis
 redisTemplate.opsForValue().set(redisKey, cacheStats, 1, TimeUnit.HOURS);
```
```
byte[] rawKey = rawKey(key);
byte[] rawValue = rawValue(value);

byte[] rawValue(Object value) {
    if (valueSerializer() == null && value instanceof byte[]) {
	return (byte[]) value;
    }
    return valueSerializer().serialize(value);
}
```

Log:
```
ERROR com.github.xiaolyuh.stats.StatsService - Cannot serialize; nested exception is org.springframework.core.serializer.support.SerializationFailedException: Failed to serialize object using DefaultSerializer; nested exception is java.lang.IllegalArgumentException: DefaultSerializer requires a Serializable payload but received an object of type [com.github.xiaolyuh.stats.CacheStatsInfo]
org.springframework.data.redis.serializer.SerializationException: Cannot serialize; nested exception is org.springframework.core.serializer.support.SerializationFailedException: Failed to serialize object using DefaultSerializer; nested exception is java.lang.IllegalArgumentException: DefaultSerializer requires a Serializable payload but received an object of type [com.github.xiaolyuh.stats.CacheStatsInfo]
	at org.springframework.data.redis.serializer.JdkSerializationRedisSerializer.serialize(JdkSerializationRedisSerializer.java:96)
	at org.springframework.data.redis.core.AbstractOperations.rawValue(AbstractOperations.java:126)
	at org.springframework.data.redis.core.DefaultValueOperations.set(DefaultValueOperations.java:254)
	at com.github.xiaolyuh.stats.StatsService.lambda$syncCacheStats$0(StatsService.java:135)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.core.serializer.support.SerializationFailedException: Failed to serialize object using DefaultSerializer; nested exception is java.lang.IllegalArgumentException: DefaultSerializer requires a Serializable payload but received an object of type [com.github.xiaolyuh.stats.CacheStatsInfo]
	at org.springframework.core.serializer.support.SerializingConverter.convert(SerializingConverter.java:68)
	at org.springframework.core.serializer.support.SerializingConverter.convert(SerializingConverter.java:35)
	at org.springframework.data.redis.serializer.JdkSerializationRedisSerializer.serialize(JdkSerializationRedisSerializer.java:94)
	... 10 common frames omitted
Caused by: java.lang.IllegalArgumentException: DefaultSerializer requires a Serializable payload but received an object of type [com.github.xiaolyuh.stats.CacheStatsInfo]
	at org.springframework.core.serializer.DefaultSerializer.serialize(DefaultSerializer.java:43)
	at org.springframework.core.serializer.support.SerializingConverter.convert(SerializingConverter.java:63)
	... 12 common frames omitted
```

**Comment by xiaolyuh123** [comment]
在最新的2.0.1已经修复了
